### ISSUE TITLE
Not Working on gnome 3.37.90

### ISSUE THREAD

**Issue by raushankumar27** [p91paul/middleclickclose#17]
Extension not working on gnome 3.37.90

**Comment by ptitjano** [comment]
I get this error with gnome-shell 3.38.0: `No JS module 'tweener' found in search path`

**Comment by p91paul** [comment]
Can you try the current master branch? There was probably a useless tweener import.

**Comment by raushankumar27** [comment]
The issue is not only with tweener. Workspace.WindowClone  has also been removed from gnome 3.38

**Comment by raushankumar27** [comment]
WindowsClone has been updated . https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1307

**Comment by p91paul** [comment]
I should have got it working. Could you please test branch gnome3.38?

**Comment by raushankumar27** [comment]
I copied the gnome 3.38 version in extension folder, but then I am not able to login into gnome-session.   System is getting freezed after entering password on login screen.

**Comment by raushankumar27** [comment]
After removing this extension folder from .local/share/gnome-shell/extensions    , system is working fine

**Comment by raushankumar27** [comment]
The new version from gnome extension website is working perfectly fine. So closing this issue
