### ISSUE TITLE
Please submit to extensions.gnome.org

### ISSUE THREAD

**Issue by kparal** [p91paul/middleclickclose#2]
The [original extension](https://extensions.gnome.org/extension/352/middle-click-to-close-in-overview/) seems to be dead for 2 years now. Could you please submit your own version to the official GNOME extensions site? It will be much easier for people to install than from github. Thanks!

**Comment by p91paul** [comment]
I did so. Actually, I asked reviewers to take over existing extension. I'll keep you informed about how this goes.

**Comment by kparal** [comment]
Thanks!

**Comment by p91paul** [comment]
I am the new maintainer of the [original extension](https://extensions.gnome.org/extension/352/middle-click-to-close-in-overview/) and I uploaded my master branch there!

**Comment by kparal** [comment]
Great news, thanks a lot :-)
