### ISSUE TITLE
Activities view automatically close when quitting an app with the wheel click

### ISSUE THREAD

**Issue by Froggy232** [p91paul/middleclickclose#20]
Hi,
Since the last update, the v1.3, the activities overview automatically close when you use the wheel to quit an app.
It was not doing it before the 1.3.
The issue is very easily reproducible, and I agree to give more informations if necessary.
Thanks you for your project, and sorry for my bad english.
Best regards

**Comment by PhilippHomann** [comment]
Happens to me too on Fedora 33 beta:
```bash
$ gnome-shell --version
GNOME Shell 3.38.1
```

**Comment by Froggy232** [comment]
I personally have downgraded to the 1.2 while waiting for a bugfix, and it work correctly now.
So, I can confirm that the problem reside in the last version change.

**Comment by p91paul** [comment]
For anyone installing through extensions.gnome.org, I deactivated v18 there, so a uninstall-reinstall should bring you back to v17 which should work.
Meanwhile I will work on a different fix for #18

**Comment by p91paul** [comment]
I entirely reverted the offending commit, so this can be closed.
