### ISSUE TITLE
rearrange delay ignored

### ISSUE THREAD

**Issue by bbo2adwuff** [p91paul/middleclickclose#21]
Seems that since you made this extension work for 3.38 the rearrange delay is not working anymore.

#### Steps to reproduce

1. Open GNOME Tweaks -> Extensions -> settings for middleclickclose.
2. Use a very high number rearrange delay for testing.

No visible change, even with a very high delay.

**Comment by p91paul** [comment]
you need to restart gnome, or disable/reenable the extension for the setting to apply

**Comment by bbo2adwuff** [comment]
Thanks for your quick reply! But I forgot to mention that I tried already to logoff -> logon and even restart the system.
But on my side (with GNOME Shell 3.38.1 and middleclickclose v18) the rearrange delay is still ignored.

Actually this issue has a low priority though ;) the extension works and it's a minor glitch that the rearrange delay is not working.
Thanks for all your effort you put in this extension!

**Comment by p91paul** [comment]
This isn't really about the delay, is it? you're actually experiencing #20, the activities view just closes on you the moment you middle click. But if you do close the window with the x button, the delay you set in the extension works.

**Comment by bbo2adwuff** [comment]
> activities view just closes on you the moment you middle click

Oh true! Sorry didn't realize before but you're right it's indeed a duplicate of #20.
