### ISSUE TITLE
Gnome 40, can't click desktop to exit overview after closing window

### ISSUE THREAD

**Issue by IvoryJam** [p91paul/middleclickclose#26]
Step to reproduce:

- have one window open
- enter overview mode
- middle click to close window

I now cannot click the desktop to close overview mode, also if I go to another workspace with a window on it, I cannot click on that window to exit overview mode.

**Comment by p91paul** [comment]
Sorry, I cannot reproduce. Tried your steps and everything works just fine.
Can you please collect journalctl logs when you get the error?

**Comment by dreua** [comment]
Never had this problem either. Are you using X server or Wayland? Just a wild guess.

**Comment by IvoryJam** [comment]
> Sorry, I cannot reproduce. Tried your steps and everything works just fine.
> Can you please collect journalctl logs when you get the error?

I've looked through it and I'm not seeing anything out of the normal really, I'm running `journalctl -f` and am not seeing errors.

@dreua I'm on Wayland... that may be why

**Comment by p91paul** [comment]
Unfortunately I cannot reproduce on Wayland....
Can you try installing manually instead of using extensions.gnome.org?
You can find instructions on https://github.com/p91paul/middleclickclose

**Comment by l3nn4rt** [comment]
GS 40.5 on Wayland here.

After using middle click to close a window, left and right buttons and scroll wheel are not responding to inputs until the pointer is moved.
Looks like the middle click event is not completed and prevents other events from getting started, while the pointer movement does complete it.

I'm getting the same behavior with both mouse and touchpad.

**Comment by p91paul** [comment]
> GS 40.5 on Wayland here.
> 
> After using middle click to close a window, left and right buttons and scroll wheel are not responding to inputs until the pointer is moved. Looks like the middle click event is not completed and prevents other events from getting started, while the pointer movement does complete it.
> 
> I'm getting the same behavior with both mouse and touchpad.

Thanks @l3nn4rt those steps allowed me to reproduce. However, after looking at this extension's code, and comparing it to Gnome code, I still have no clue how to fix this. Middle clicking now calls the very same function as the actual close button, but behavior is different and blocks subsequent events until mouse moves...

**Comment by p91paul** [comment]
With the latest version on Gnome 43 I can no longer reproduce this. Can someone confirm this is fine now?

**Comment by IvoryJam** [comment]
Yes, everything works as intended now. I believe originally it was the DING extension I was using but that's been fixed
