### ISSUE TITLE
"Incompatible" on Gnome 41

### ISSUE THREAD

**Issue by djshaji** [p91paul/middleclickclose#27]
I love this extension and really can't live without it. But it shows as _**incompatible**_ with **GNOME-41.0**. Kindly update, with much thanks.

It really should be default behaviour or at least an in-built option! Thanks so much!

**Comment by p91paul** [comment]
do you know if it works with manual installation (and/or possibly editing metadata.json to add 41 as compatible version)? maybe it's just the version check and not an actual code problem.

**Comment by Mershl** [comment]
@p91paul No hurry, was just wondering: Is the GNOME 41 release currently in the review process on https://extensions.gnome.org ?

**Comment by djshaji** [comment]
Works on manual installation now, although showing as incompatible on the extensions website. 

Much thanks man! Really indispensable extension, this!

**Comment by p91paul** [comment]
Released on extensions.gnome.org, without testing since I don't have 41 available.

**Comment by Mershl** [comment]
Thank you @p91paul, just installed from extensions.gnome.org. I'll be testing it on my main dev machine (Fedora 35, Gnome 41). If I notice errors/warnings/weird behaviour I'll report it here.
