### ISSUE TITLE
Unable to install extension: "Error"

### ISSUE THREAD

**Issue by djshaji** [p91paul/middleclickclose#31]
So while my manual installation was working perfectly, GNOME gave a  notification that the extension can be upgraded. But when I tried, it gave an error.

Even after I uninstalled it, I was unable to install it again.

Will try to install it manually again.
![Screenshot](https://user-images.githubusercontent.com/17184025/140104233-d6149798-8764-4598-8fc0-80e6a5211ea0.png)

**Comment by djshaji** [comment]
So I installed it manually also, but it isn't being turned on anymore, neither in the web interface nor the "extensions" app :(

![Screenshot from 2021-11-03 23-22-02](https://user-images.githubusercontent.com/17184025/140165035-ef25810e-9197-452c-99c4-27786d9fdefb.png)

**Comment by p91paul** [comment]
Gnome is unable to reload extensions after they are first loaded. It requires restarting the shell.
On Xorg Alt+F2 -> r -> enter is enough; on wayland, you need to log off or restart.
