### ISSUE TITLE
Like close button, this should "minimize Steam to tray", not close it entirely

### ISSUE THREAD

**Issue by wojpawlik** [p91paul/middleclickclose#32]

**Comment by wojpawlik** [comment]
<kbd>Alt+F4</kbd> unexpectedly quits Steam too...

**Comment by dreua** [comment]
I think this is a Steam issue, not a middle click close one.

**Comment by p91paul** [comment]
Yeah, there's nothing this extension can do if steam reacts to the close signal wrong, sorry.
