### ISSUE TITLE
Readme is outdated (Tweak Tool -> Extensions)

### ISSUE THREAD

**Issue by dreua** [p91paul/middleclickclose#39]
I'm on Gnome 43, not sure when exactly this changed. The Tweak tool does no longer have the "Extensions" menu, "Extensions" is its own Gnome application in the meantime.

*Background story, not relevant:*
I just upgraded from Fedora Linux 35 to 37 and instantly missed the middleclick-close functionality. After finally finding the "Extensions" Application it showed an available update for this and after a relogin everything worked as intended :tada: Thank you for maintaining this!

**Comment by p91paul** [comment]
README updated, thanks!
