### ISSUE TITLE
prepare to Gnome 45/ESM

### ISSUE THREAD

**Issue by caetano-m** [p91paul/middleclickclose#44]
So Gnome 45 will move to ESM, that means all extensions will be broken when the new Shell version arrive. There are some guides on how to port extensions to ESM, eg.: https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm and https://www.youtube.com/watch?v=OBnMl8Jk_Rg. 

There's also a [matrix channel](https://matrix.to/#/#extensions:gnome.org) with an active community willing to help other extension developers with this transition.

**Comment by p91paul** [comment]
Thanks for the pointers; I'll see if I can find the time to work on this, otherwise I hope some nice guy will step in with a pull request.

**Comment by gtsiam** [comment]
@GuillaumeAmat We'll publish it soon; we're looking to do an ownership transfer, but that is going to take a few days.

For now, feel free to clone the repo and run `make install` (This won't install system-wide, just for your user)
