### ISSUE TITLE
Gnome 45 support

### ISSUE THREAD

**Issue by gtsiam** [p91paul/middleclickclose#50]
We're currently waiting for the [review](https://extensions.gnome.org/review/46765) of version 29, which includes Gnome 45 support.

I'm making this issue until we manage to publish on EGO (extensions.gnome.org), because people keep asking.

Subscribe to the issue if you want to be notified.

In the meantime, if you're comfortable with the command line, you can run `make install` within a clone of this repo.

**Comment by p91paul** [comment]
New version was approved on extensions.gnome.org!
