### ISSUE TITLE
Make this extension possible to translate?

### ISSUE THREAD

**Issue by jurf** [p91paul/middleclickclose#6]
Hey, I would like to translate this extension, could you set it up for it? Thanks.

**Comment by p91paul** [comment]
I would like to, but I can't set a schedule right now!

**Comment by DoctorJellyface** [comment]
Thanks, maybe I'll look into it if I find time sooner.

**Comment by DoctorJellyface** [comment]
OK, found several ways how to do it, the best way would probably be to created a `po` directory in root and keep the `mo` files in a `locale` folder in the `middleclickclose@paolo.tranquilli.gmail.com` one.

**Comment by p91paul** [comment]
If you can look into it, I'll accept pull requests gladly!

**Comment by p91paul** [comment]
We now have French, Italian and Slovak translations in the middleclickclose@paolo.tranquilli.gmail.com/locale folder!
