### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Eggbertx** [p91paul/middleclickclose#9]
As of GNOME Shell version 3.20.0-2, this extension (and several others) is outdated and can't be installed.

**Comment by p91paul** [comment]
I just saw that 3.20 hit arch linux, so I'll soon upgrade and test it. Have you tried editing metadata.json to add 3.20 to supported versions?

**Comment by p91paul** [comment]
I updated the extension and submitted it for review on e.g.o!
